-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIGJdvoOUngVGsSWmWbKG8MKc9rpi/W99TODZsFnTqYS5oAoGCCqGSM49
AwEHoUQDQgAEaoMwoX9qAysyIWNurKclMx4qS07jy8hY9dDw1uGAbCKAm/ZsXcgp
H69avjNgWuJzVqpwhmaYlIWArpaCflM4Ow==
-----END EC PRIVATE KEY-----
