-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgYl2+g5SeBUaxJaZZ
sobwwpz2umL9b31M4NmwWdOphLmhRANCAARqgzChf2oDKzIhY26spyUzHipLTuPL
yFj10PDW4YBsIoCb9mxdyCkfr1q+M2Ba4nNWqnCGZpiUhYCuloJ+Uzg7
-----END PRIVATE KEY-----
