package com.mayo.sync.grpc;

import io.grpc.BindableService;
import io.grpc.CallOptions;
import io.grpc.Channel;
import io.grpc.MethodDescriptor;
import io.grpc.ServerServiceDefinition;
import io.grpc.ServiceDescriptor;
import io.grpc.stub.AbstractAsyncStub;
import io.grpc.stub.AbstractBlockingStub;
import io.grpc.stub.AbstractFutureStub;
import io.grpc.stub.AbstractStub;
import io.grpc.stub.StreamObserver;

/**
 * Simplified gRPC service base class for sync operations
 */
public class SyncServiceGrpc {

    private static final String SERVICE_NAME = "com.mayo.sync.grpc.SyncService";

    public static class SyncServiceImplBase implements BindableService {

        public StreamObserver<SyncRequestProto> streamSync(StreamObserver<SyncResponseProto> responseObserver) {
            throw new UnsupportedOperationException("Not implemented");
        }

        public void realTimeUpdate(SyncUpdate request, StreamObserver<AckResponse> responseObserver) {
            throw new UnsupportedOperationException("Not implemented");
        }

        @Override
        public ServerServiceDefinition bindService() {
            return ServerServiceDefinition.builder(SERVICE_NAME).build();
        }
    }

    // Stub classes would be generated by protoc, simplified here
    public static abstract class SyncServiceStub extends AbstractStub<SyncServiceStub> {
        protected SyncServiceStub(Channel channel, CallOptions callOptions) {
            super(channel, callOptions);
        }

        @Override
        protected SyncServiceStub build(Channel channel, CallOptions callOptions) {
            return new SyncServiceStub(channel, callOptions) {};
        }
    }

    public static final class SyncServiceBlockingStub extends AbstractBlockingStub<SyncServiceBlockingStub> {
        protected SyncServiceBlockingStub(Channel channel, CallOptions callOptions) {
            super(channel, callOptions);
        }

        @Override
        protected SyncServiceBlockingStub build(Channel channel, CallOptions callOptions) {
            return new SyncServiceBlockingStub(channel, callOptions);
        }
    }

    public static final class SyncServiceFutureStub extends AbstractFutureStub<SyncServiceFutureStub> {
        protected SyncServiceFutureStub(Channel channel, CallOptions callOptions) {
            super(channel, callOptions);
        }

        @Override
        protected SyncServiceFutureStub build(Channel channel, CallOptions callOptions) {
            return new SyncServiceFutureStub(channel, callOptions);
        }
    }
}